- id: doi:10.1099/mgen.0.000805
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/8/4/mgen000805-f4.gif
  extra-links:
    - type: website
      link: https://www.lstmed.ac.uk/news-events/news/researchers-from-lstm-complete-analysis-of-wolbachia-bacterial-endosymbiont-strains
  tags:
    - Wolbachia
    - Anopheles

- id: doi:10.1099/mgen.0.000789
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/8/4/mgen000805-f4.gif
  extra-links:
    - type: manubot
      link: https://www.lstmed.ac.uk/news-events/news/researchers-from-lstm-complete-analysis-of-wolbachia-bacterial-endosymbiont-strains
    - type: source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: manubot
      link: https://greenelab.github.io/scihub-manuscript/
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source
