- id: doi:10.1101/2024.08.26.609643
  image: images/protein_microarray.jpg
  tags: 
    - Antimicrobial Resistance
    - Sub-saharan Africa
    - Typhi

- id: doi:10.1172/JCI168789
  image: images/protein_microarray.jpg
  tags: 
    - Antimicrobial Resistance
    - Vaccine Targets
    - Surface Proteins

- id: doi:10.1101/2024.04.02.24305201
  image: images/Gallichan.jpg
  tags:
    - Antimicrobial Resistance
    - E. coli

- id: doi:10.1101/2024.01.15.24301199
  image: images/bbsrc_fig_3.jpg
  tags:
    - Antimicrobial Resistance
    - E. coli
  
- id: doi:10.1136/bmjgh-2023-014743
  image: https://www.lstmed.ac.uk/sites/default/files/styles/mc-580-16x9-node/public/content/news-articles/images/image_0_0_0.png?itok=Kw5zGK1k
  tags:
    - Research Integrity
    - Parachute Research
    - Review/Editorial

- id: doi:10.1101/2023.11.22.568226
  image: https://www.biorxiv.org/content/biorxiv/early/2023/12/15/2023.11.22.568226/F3.medium.gif
  tags:
    - Anopheles
    - Insecticide Resistance
    
- id: doi:10.1101/2023.10.04.560816
  image: images/Picture 1.png
  tags:
    - Aedes
    - Anopheles
    - Culex
    - Microbiome
    - Resource

- id: doi:10.1186/s13073-024-01342-3
  image: images/Fig5.png
  tags:
    - Antimicrobial Resistance
    - Klebsiella
    - Sub-saharan Africa
    - Surface Polysaccharides
    - Vaccine Targets

- id: doi:10.21203/rs.3.rs-3265990/v1
  image: images/Fig3_virome.png
  tags:
    - virome
    - Nematodes

- id: doi:10.1111/1462-2920.16576
  image: images/Fig1_2023.03.16.532926.png
  tags:
    - Aedes
    - Microbiome
    - Resource
    
- id: doi:10.12688/wellcomeopenres.19155.2
  image: https://user-images.githubusercontent.com/80700844/148986377-3df4a613-fd43-49e1-9093-cc631a5a0d68.png
  tags:
    - Aedes
    - Microbiome
    - Method

- id: doi:10.1099/mgen.0.000805
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/8/4/mgen000805-f4.gif
  extra-links:
    - type: journal
      link: https://www.lstmed.ac.uk/news-events/news/researchers-from-lstm-complete-analysis-of-wolbachia-bacterial-endosymbiont-strains
      text: LSTM press release
  tags:
    - Wolbachia
    - Anopheles

- id: doi:10.1099/mgen.0.000789
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/8/4/mgen000789-f4.gif
  tags:
    - Antimicrobial Resistance
    - E.coli

- id: doi:10.1099/mgen.0.000778
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/8/3/mgen000778-f5.gif
  tags:
    - Antimicrobial Resistance
    - Klebsiella
    - Sub-saharan Africa
    - Surface Polysaccharides
    - Vaccine Targets
    
- id: doi:10.1371/journal.pgph.0000160
  image: https://www.lstmed.ac.uk/sites/default/files/styles/mc-580-16x9-node/public/content/news-articles/images/image_0_0_0.png?itok=Kw5zGK1k
  extra-links:
    - type: journal
      link: https://www.lstmed.ac.uk/news-events/news/lstm-researchers-alongside-an-international-team-promote-equitable-authorship
      text: LSTM press release
  tags:
    - Research Integrity
    - Parachute Research
    - Review/Editorial
    
- id: doi:10.1099/mgen.0.000722
  image: https://www.lstmed.ac.uk/sites/default/files/styles/mc-580-16x9-node/public/content/news-articles/images/image_0_0_0.png?itok=Kw5zGK1k
  tags:
    - Research Integrity
    - Parachute Research
    - Review/Editorial
    
- id: doi:10.1371/journal.pgen.1009970
  image: https://journals.plos.org/plosgenetics/article/figure/image?size=medium&id=10.1371/journal.pgen.1009970.g004
  tags:
    - Insecticide Resistance
    - Anopheles

- id: doi:10.1111/anae.15597
  image: https://www.lstmed.ac.uk/sites/default/files/styles/mc-580-16x9-node/public/content/news-articles/images/image_0_0_0.png?itok=Kw5zGK1k
  extra-links:
    - type: journal
      link: https://www.lstmed.ac.uk/news-events/news/lstm-researchers-collaborate-in-multi-country-consensus-statement-to-promote
      text: LSTM press release
  tags:
    - Research Integrity
    - Parachute Research
    
- id: doi:10.1371/journal.pgen.1009586
  image: https://journals.plos.org/plosgenetics/article/figure/image?size=medium&id=10.1371/journal.pgen.1009586.g011
  tags:
    - Bacterial Cell Envelope
    - Surface Proteins

- id: doi:10.1038/s41467-022-32929-2
  image: https://www.biorxiv.org/content/biorxiv/early/2022/01/11/2022.01.11.475790/F5.large.jpg?width=800&height=600&carousel=1
  tags:
    - Bacterial Cell Envelope
    - Resource

- id: doi:10.1038/s41564-022-01216-7
  image: https://www.medrxiv.org/content/medrxiv/early/2021/10/11/2021.10.08.21264775/F1.large.jpg?width=800&height=600&carousel=1
  tags:
    - Antimicrobial Resistance
    - E.coli
    - Klebsiella
    - Sub-saharan Africa
    - Genome Epidemiology
  extra-links:
    - type: journal
      link: https://www.lstmed.ac.uk/news-events/news/new-lstm-led-research-sheds-light-on-how-antibiotic-use-can-help-drive-drug
      text: LSTM press release

- id: doi:10.1099/mgen.0.001035
  image: https://www.biorxiv.org/content/biorxiv/early/2021/10/07/2021.10.07.463523/F4.large.jpg?width=800&height=600&carousel=1
  extra-links:
  tags:
    - Antimicrobial Resistance
    - E.coli
    - Sub-saharan Africa
      
- id: doi:10.1101/866897
  image: https://www.biorxiv.org/content/biorxiv/early/2020/01/16/866897/F6.large.jpg?width=800&height=600&carousel=1
  extra-links:
  tags:
    - Aedes
    - Microbiome
    
- id: doi:10.1099/mgen.0.000703
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/7/11/mgen000703-f5.gif
  tags:
    - Antimicrobial Resistance
    - Sub-saharan Africa
    - Klebsiella
    - Genome Epidemiology

- id: doi:10.1099/mgen.0.000691
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/7/11/mgen000691-f1.gif
  tags:
    - Method
    - Genome Epidemiology

- id: doi:10.1099/mgen.0.000670
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/7/9/mgen000670-f1.gif
  tags:
    - Method
    - Resource
    - E. coli
    
- id: doi:10.1093/cid/ciab745
  image: images/Typhi_Blantyre.png
  tags:
    - Typhi
    - Method
    - Genome Epidemiology
    - Sub-saharan Africa
    
- id: doi:10.1128/mBio.01480-21
  image: https://journals.asm.org/cms/10.1128/mBio.01480-21/asset/cf1a8900-8b19-4780-9684-9bebc06e13d2/assets/images/large/mbio.01480-21-f003.jpg
  tags:
    - Bacterial Cell Envelope
    - Surface Proteins
    
- id: doi:10.1186/s12879-021-06435-7
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8336361/bin/12879_2021_6435_Fig2_HTML.jpg
  tags:
    - Antimicrobial Resistance
    - E. coli
    - Review/Editorial

- id: doi:10.1016/j.cub.2021.03.056
  image: https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/79f7da4c-7ea1-4280-8bc1-add2daf2c875/gr2.jpg
  tags:
    - Anopheles
    - Wolbachia

- id: doi:10.1038/s41467-021-21870-5
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7940655/bin/41467_2021_21870_Fig2_HTML.jpg
  tags:
    - Antimicrobial Resistance
    - Vaccine Targets

- id: doi:10.1099/mgen.0.000499
  image: https://www.microbiologyresearch.org/docserver/ahah/fulltext/mgen/7/2/mgen000499-f1_thmb.gif
  tags:
    - Method
    - E. coli
    - Resource
    
- id: doi:10.1038/s41396-020-00763-3
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7852612/bin/41396_2020_763_Fig4_HTML.jpg
  tags:
    - Aedes
    - Microbiome
    - Culex

- id: doi:10.7554/eLife.62614
  image: https://iiif.elifesciences.org/lax/62614%2Felife-62614-fig2-v2.tif/full/1500,/0/default.jpg
  tags:
    - Bacterial Cell Envelope
    - Surface Proteins

- id: doi:10.1093/nar/gkaa198
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7192599/bin/gkaa198fig3.jpg
  tags:
    - Klebsiella
    - Resource

- id: doi:10.3389/fmicb.2020.00548
  image: https://www.frontiersin.org/files/Articles/513234/fmicb-11-00548-HTML-r1/image_m/fmicb-11-00548-g002.jpg
  tags:
    - Acinetobacter
    - Antimicrobial Resistance
    - Surface Polysaccharides
    - Vaccine Targets
    - Immune System

- id: doi:10.1084/jem.20180649
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7041704/bin/JEM_20180649_Fig1.jpg
  tags:
    - Immune System
    - Resource

- id: doi:10.1371/journal.pntd.0007883
  image: https://journals.plos.org/plosntds/article/figure/image?size=inline&id=10.1371/journal.pntd.0007883.g001
  tags:
    - Aedes
    - Microbiome

- id: doi:10.1371/journal.pone.0221960
  image: https://journals.plos.org/plosone/article/figure/image?size=inline&id=10.1371/journal.pone.0221960.g001
  tags:
    - Antimicrobial Resistance
    - Klebsiella
    - E. coli
    - Enterobacter
    - Latin America

- id: doi:10.1186/s13059-019-1785-1
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6717969/bin/13059_2019_1785_Fig4_HTML.jpg
  tags:
    - Antimicrobial Resistance
    - Klebsiella
    - Enterobacter
    - Genome Epidemiology

- id: doi:10.1038/s41467-019-11844-z
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6753159/bin/41467_2019_11844_Fig2_HTML.jpg
  tags:
    - Antimicrobial Resistance
    - Typhimurium
    - Genome Epidemiology
    - Sub-saharan Africa

- id: doi:10.1038/s41591-019-0505-4
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6892374/bin/41591_2019_505_Fig1_HTML.jpg
  tags:
    - Typhi
    - Surface Polysaccharides
    - Vaccine Targets
    
- id: doi:10.1099/mgen.0.000266
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6562249/bin/mgen-5-266-g001.jpg
  tags:
    - Antimicrobial Resistance
    - Klebsiella
    - Latin America
    - Genome Epidemiology
    
- id: doi:10.1128/aem.01062-22 
  image: https://www.biorxiv.org/content/biorxiv/early/2022/05/26/2022.05.26.493619/F2.large.jpg
  tags:
    - Insect-specific viruses
    - Aedes

- id: doi:10.1186/s12936-022-04176-9 
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/9164396/bin/12936_2022_4176_Fig1_HTML.jpg
  tags:
    - Malaria
    - Anopheles
    
