- id: doi:10.1099/mgen.0.000805
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/8/4/mgen000805-f4.gif
  extra-links:
    - type: website
      link: https://www.lstmed.ac.uk/news-events/news/researchers-from-lstm-complete-analysis-of-wolbachia-bacterial-endosymbiont-strains
      text: LSTM press release
  tags:
    - Wolbachia
    - Anopheles

- id: doi:10.1099/mgen.0.000789
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/8/4/mgen000789-f4.gif
  tags:
    - AMR
    - E.coli

- id: doi:10.1099/mgen.0.000778
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/8/3/mgen000778-f5.gif
  tags:
    - AMR
    - Klebsiella
    - Sub-saharan Africa
    - Surface Polysaccharides
    
- id: doi:10.1371/journal.pgph.0000160
  image: https://www.microbiologyresearch.org/docserver/fulltext/mgen/8/4/mgen000805-f4.gif
  extra-links:
    - type: website
      link: https://www.lstmed.ac.uk/news-events/news/lstm-researchers-alongside-an-international-team-promote-equitable-authorship
      text: LSTM press release
  tags:
    - Research Integrity
    - Parachute Research
